const READONLY = 'readonly';

export const CORRECTNESS_LINT_FILES = Object.freeze( [
	'packages/contract/src/**/*.js',
	'packages/plugin/src/**/*.js',
	'packages/runtime/src/**/*.js',
	'packages/examples/batch/**/*.{js,mjs}',
	'packages/site/src/**/*.js',
	'packages/site/scripts/**/*.{js,mjs}',
	'scripts/**/*.{js,mjs}',
] );

export const CORRECTNESS_LINT_IGNORES = Object.freeze( [
	'**/node_modules/**',
	'**/dist/**',
	'**/build/**',
	'**/artifacts/**',
	'**/results/**',
	'packages/site/public/**',
	'packages/plugin/src/vendor/**',
	'.claude/worktrees/**',
	'**/.claude/worktrees/**',
	'.worktrees/**',
	'**/.worktrees/**',
] );

const COMMON_GLOBALS = Object.freeze( {
	AbortController: READONLY,
	AbortSignal: READONLY,
	Blob: READONLY,
	clearInterval: READONLY,
	clearTimeout: READONLY,
	console: READONLY,
	crypto: READONLY,
	DOMException: READONLY,
	fetch: READONLY,
	File: READONLY,
	FormData: READONLY,
	Headers: READONLY,
	performance: READONLY,
	queueMicrotask: READONLY,
	Request: READONLY,
	Response: READONLY,
	setInterval: READONLY,
	setTimeout: READONLY,
	structuredClone: READONLY,
	TextDecoder: READONLY,
	TextEncoder: READONLY,
	URL: READONLY,
	URLSearchParams: READONLY,
} );

const NODE_GLOBALS = Object.freeze( {
	Buffer: READONLY,
	clearImmediate: READONLY,
	process: READONLY,
	setImmediate: READONLY,
} );

const BROWSER_GLOBALS = Object.freeze( {
	atob: READONLY,
	Audio: READONLY,
	btoa: READONLY,
	cancelAnimationFrame: READONLY,
	createImageBitmap: READONLY,
	customElements: READONLY,
	devicePixelRatio: READONLY,
	document: READONLY,
	Event: READONLY,
	EventTarget: READONLY,
	getComputedStyle: READONLY,
	GPUBuffer: READONLY,
	GPUBufferUsage: READONLY,
	GPUCanvasContext: READONLY,
	GPUColorWrite: READONLY,
	GPUComputePipeline: READONLY,
	GPUDevice: READONLY,
	GPUMapMode: READONLY,
	GPUShaderStage: READONLY,
	GPUTexture: READONLY,
	GPUTextureUsage: READONLY,
	GPUTextureView: READONLY,
	HTMLElement: READONLY,
	HTMLVideoElement: READONLY,
	history: READONLY,
	Image: READONLY,
	ImageData: READONLY,
	location: READONLY,
	localStorage: READONLY,
	matchMedia: READONLY,
	MutationObserver: READONLY,
	navigator: READONLY,
	OffscreenCanvas: READONLY,
	requestAnimationFrame: READONLY,
	ResizeObserver: READONLY,
	screen: READONLY,
	self: READONLY,
	window: READONLY,
	Worker: READONLY,
	WorkerGlobalScope: READONLY,
} );

const CORRECTNESS_RULES = Object.freeze( {
	'constructor-super': 'error',
	'for-direction': 'error',
	'getter-return': 'error',
	'no-async-promise-executor': 'error',
	'no-case-declarations': 'error',
	'no-class-assign': 'error',
	'no-compare-neg-zero': 'error',
	'no-cond-assign': 'error',
	'no-const-assign': 'error',
	'no-constant-binary-expression': 'error',
	'no-constant-condition': [ 'error', { checkLoops: false } ],
	'no-control-regex': 'error',
	'no-debugger': 'error',
	'no-dupe-args': 'error',
	'no-dupe-class-members': 'error',
	'no-dupe-else-if': 'error',
	'no-dupe-keys': 'error',
	'no-duplicate-case': 'error',
	'no-duplicate-imports': 'error',
	'no-empty-character-class': 'error',
	'no-empty-pattern': 'error',
	'no-ex-assign': 'error',
	'no-extra-boolean-cast': 'error',
	'no-fallthrough': 'error',
	'no-func-assign': 'error',
	'no-import-assign': 'error',
	'no-inner-declarations': 'error',
	'no-invalid-regexp': 'error',
	'no-irregular-whitespace': 'error',
	'no-loss-of-precision': 'error',
	'no-misleading-character-class': 'error',
	'no-new-native-nonconstructor': 'error',
	'no-new-symbol': 'error',
	'no-obj-calls': 'error',
	'no-prototype-builtins': 'error',
	'no-regex-spaces': 'error',
	'no-self-assign': 'error',
	'no-setter-return': 'error',
	'no-shadow-restricted-names': 'error',
	'no-sparse-arrays': 'error',
	'no-this-before-super': 'error',
	'no-undef': 'error',
	'no-unexpected-multiline': 'error',
	'no-unreachable': 'error',
	'no-unreachable-loop': 'error',
	'no-unsafe-finally': 'error',
	'no-unsafe-negation': 'error',
	'no-unsafe-optional-chaining': 'error',
	'no-unused-private-class-members': 'error',
	'no-useless-backreference': 'error',
	'no-with': 'error',
	'require-yield': 'error',
	'use-isnan': 'error',
	'valid-typeof': 'error',
} );

export default [
	{ ignores: CORRECTNESS_LINT_IGNORES },
	{
		name: 'authored-javascript-correctness',
		files: CORRECTNESS_LINT_FILES,
		linterOptions: { reportUnusedDisableDirectives: 'off' },
		languageOptions: {
			ecmaVersion: 'latest',
			sourceType: 'module',
			globals: COMMON_GLOBALS,
		},
		rules: CORRECTNESS_RULES,
	},
	{
		name: 'node-authored-javascript-globals',
		files: [
			'packages/contract/src/**/*.js',
			'packages/plugin/src/**/*.js',
			'packages/examples/batch/**/*.{js,mjs}',
			'packages/site/scripts/**/*.{js,mjs}',
			'scripts/**/*.{js,mjs}',
		],
		languageOptions: { globals: NODE_GLOBALS },
	},
	{
		name: 'browser-authored-javascript-globals',
		files: [
			'packages/plugin/src/**/*.js',
			'packages/runtime/src/**/*.js',
			'packages/examples/batch/**/*.{js,mjs}',
			'packages/site/src/**/*.js',
			'packages/site/scripts/**/*.{js,mjs}',
		],
		languageOptions: { globals: BROWSER_GLOBALS },
	},
];
