export const MATERIAL_TEXTURE_PROPS = Object.freeze( [
	'map',
	'alphaMap',
	'aoMap',
	'bumpMap',
	'displacementMap',
	'emissiveMap',
	'envMap',
	'lightMap',
	'normalMap',
	'specularMap',
	'roughnessMap',
	'metalnessMap',
	'gradientMap',
	'matcap',
	'clearcoatMap',
	'clearcoatNormalMap',
	'clearcoatRoughnessMap',
	'iridescenceMap',
	'iridescenceThicknessMap',
	'sheenColorMap',
	'sheenRoughnessMap',
	'specularColorMap',
	'specularIntensityMap',
	'transmissionMap',
	'thicknessMap',
	'anisotropyMap',
] );

export const NODE_GRAPH_TEXTURE_KEYS = Object.freeze( [
	'colorNode',
	'normalNode',
	'outputNode',
	'backdropNode',
	'backdropAlphaNode',
	'roughnessNode',
	'metalnessNode',
	'emissiveNode',
	'opacityNode',
	'alphaTestNode',
	'vertexNode',
	'positionNode',
	'geometryNode',
	'mrtNode',
	'envNode',
	'lightNode',
	'aoNode',
	'iorNode',
	'iridescenceNode',
	'iridescenceIORNode',
	'iridescenceThicknessNode',
	'specularIntensityNode',
	'specularColorNode',
	'sheenColorNode',
	'sheenRoughnessNode',
	'clearcoatNode',
	'clearcoatRoughnessNode',
	'clearcoatNormalNode',
	'transmissionNode',
	'thicknessNode',
	'attenuationDistanceNode',
	'attenuationColorNode',
	'offsetNode',
	'scatteringNode',
] );

export const MATERIAL_NODE_TEXTURE_KEYS = Object.freeze( [
	...new Set( [
		...NODE_GRAPH_TEXTURE_KEYS,
		'fragmentNode',
		'maskNode',
		'maskShadowNode',
		'receivedShadowPositionNode',
		'castShadowPositionNode',
		'castShadowNode',
	] ),
] );
